### ISSUE TITLE
Can ConvertExtension be derived from DynamicResourceExtension?

### ISSUE THREAD

**Issue by shcholeh** [hexinnovation/MathConverter#6] opened 2023-06-28 12:00 UTC
Can **ConvertExtension** be derived from **DynamicResourceExtension**, because at design getting error message:

<details>
<summary>System.ArgumentException</summary>
'ConvertExtension' is not valid for Setter.Value. The only supported MarkupExtension types are DynamicResourceExtension and BindingBase or derived types.
   at System.Windows.Setter.Seal()
   at System.Windows.SetterBaseCollection.Seal()
   at System.Windows.TriggerBase.ProcessSettersCollection(SetterBaseCollection setters)
   at System.Windows.DataTrigger.Seal()
   at System.Windows.TriggerCollection.Seal()
   at System.Windows.Style.Seal()
   at System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   at System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.Controls.TextBox.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.RunApplication()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.<>c__DisplayClass3_0.<Main>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
</details>

Just because used Extension:
```                
                <Setter Property="materialDesign:TextFieldAssist.SuffixText" 
                        Value="{math:Convert Expression='$`{(y ? `ALL ` : ``)}{x} row{(x == 1 ? `` : `s`)}`', 
                            x={Binding Count, RelativeSource={RelativeSource Mode=FindAncestor, AncestorType={x:Type database:DBDataGridQuery}}},
                            y={Binding IsAllLoaded, RelativeSource={RelativeSource Mode=FindAncestor, AncestorType={x:Type database:DBDataGridQuery}}}}"/>
```
instead of MultiBinding:
```
                <Setter Property="materialDesign:TextFieldAssist.SuffixText" >
                    <Setter.Value>
                        <MultiBinding Converter="{math:MathConverter}" ConverterParameter="$`{(y ? `ALL ` : ``)}{x} row{(x == 1 ? `` : `s`)}`">
                            <Binding Path="Count" RelativeSource="{RelativeSource Mode=FindAncestor, AncestorType={x:Type database:DBDataGridQuery}}" />
                            <Binding Path="IsAllLoaded" RelativeSource="{RelativeSource Mode=FindAncestor, AncestorType={x:Type database:DBDataGridQuery}}" />
                        </MultiBinding>
                    </Setter.Value>
                </Setter>
```

**Comment by timothylcooke** [comment] 2023-06-29 00:41
Interesting. I gather this is WPF. I can't make it be a DynamicResourceExtension, but in theory, I can make it extend MultiBinding directly, at least in WPF. I'll try to play around with that soon.

**Comment by timothylcooke** [comment] 2023-06-29 15:39
I'm unable to reproduce. Please see [my ConvertExtensionTest repository](https://github.com/timothylcooke/ConvertExtensionTest/blob/0e1cb8ec11bea00701e2731038b7df7ae5cbd047/src/MainWindow.xaml#L20).

What am I doing wrong? Maybe with a different version of dotnet, or that library, or Visual Studio? Can you provide more details?

**Comment by shcholeh** [comment] 2023-06-29 16:31
Sorry! I didn't want to write a lot misleading info here.
Possibly that ugly warning is version/platform dependent. I'm at VS 2019 v.16.11.26. It is not 1st thing that appears only on loading designer for xaml and people as usual use some hacks for that.

Here everything was working in the evening - runtime, designtime (I even uploaded and distributed project), but in the morning I spent and hour to understand why designer doesn't want to load for certain xaml.

Here found similar case and explanations
[https://stackoverflow.com/questions/12881020/0-is-not-valid-for-setter-value-the-only-supported-markupextension-types-are](url)

Here is only more angry man
[https://stackoverflow.com/questions/51190307/using-a-markup-extension-as-value-of-property-setter-in-xaml-0-is-not-valid-f](url)

Here something similar with DynamicResourceExtension hack solution
[https://stackoverflow.com/questions/52946703/markupextension-is-not-valid-for-setter-value-the-only-supported-markupextensio](url)

Thank you a lot for nice MathConverter, its functionality and flexibility that came with v2 with custom functions, conversion.
I moved to v2 because of need of playing with Padding and Margin (Thickness) like here:
```
Padding="{math:Convert Expression='ConvertType($`2 0 {x} 0`, y)', x={Binding Source={x:Static SystemParameters.VerticalScrollBarWidth}}, y={Binding Source={x:Type Thickness}} }"
```
I'm happy with it like it is. That extension is just a question of beauty of one line code. 
Thanks for paying attention to my case.

**Comment by timothylcooke** [comment] 2023-06-29 19:26
I'm glad you like MathConverter. Personally, I use it in just about every project I make.

In your example, you shouldn't need ConvertType at all, given that you're converting to Padding, which has a target type of Thickness. You should be able to do that one with just:

``Padding="{math:Convert '2,0,x,0', x={Binding Source={x:Static SystemParameters.VerticalScrollBarWidth}}}"``

or:

``Padding="{Binding ConverterParameter='2,0,x,0', Source={x:Static SystemParameters.VerticalScrollBarWidth}, Converter={StaticResource Math}}"``

**Comment by timothylcooke** [comment] 2023-06-29 19:40
As far as the exception you're getting, it's too bad you're running into design-time issues.

Can you try using the [`2.2.1-preview` Nuget package](https://www.nuget.org/packages/MathConverter/2.2.1-preview)? I refactored `ConvertExtension` to directly inherit `MultiBinding` (and therefore `BindingBase`). It sounds like that should resolve your issue.

FWIW, this change only affects WPF, not Maui or Xamarin Forms.

**Comment by shcholeh** [comment] 2023-06-30 18:10
> As far as the exception you're getting, it's too bad you're running into design-time issues.
> 
> Can you try using the [`2.2.1-preview` Nuget package](https://www.nuget.org/packages/MathConverter/2.2.1-preview)? I refactored `ConvertExtension` to directly inherit `MultiBinding` (and therefore `BindingBase`). It sounds like that should resolve your issue.
> 
> FWIW, this change only affects WPF, not Maui or Xamarin Forms.

You were fast. Everything went smooth. Design time exception gone! Thank you.

**Comment by shcholeh** [comment] 2023-06-30 18:26
> I'm glad you like MathConverter. Personally, I use it in just about every project I make.
> 
> In your example, you shouldn't need ConvertType at all, given that you're converting to Padding, which has a target type of Thickness. You should be able to do that one with just:
> 
> `Padding="{math:Convert '2,0,x,0', x={Binding Source={x:Static SystemParameters.VerticalScrollBarWidth}}}"`
> 
> or:
> 
> `Padding="{Binding ConverterParameter='2,0,x,0', Source={x:Static SystemParameters.VerticalScrollBarWidth}, Converter={StaticResource Math}}"`

Thanks! I knew that it will become more simple with yours aid. 
The history of that binding is long: starting with own converter, then several variables dependent **MathConverter** in MultiBinding (a try to modify existing Padding with OneTime conversion), then MultiBinding that combines constant values, then a number of trials of simplify but still being in string so needed convertor to Thickness. 
Possibly you will implement operators for Thickness - often there is a need to modify/compute one of values of Padding or Margin and lazy of writing **CustomFunction** for each case. However **ConvertExtension** and implicit conversion of comma separated values to Thickness simplifies enough most of cases. Thanks.
P.S.: If you are not tired of me I'll create one more case in a while. This one may be closed.

**Comment by timothylcooke** [comment] 2023-07-02 02:06
To summarize, this is fixed in 2.2.1-preview. I will probably make a full release in the next week or so, and I will close the issue once a full release is published. This bug only affects the designer, and only on WPF.

**Comment by timothylcooke** [comment] 2023-07-02 02:19
@shcholeh if you want to open more issues, I'm happy to help out. I've been thinking about making a discord server for help with conversions. For what it's worth, you very rarely need to use ConvertType. Mathconverter will implicitly convert to the type of the target property for you.

In the example you gave, ``ConverterParameter='$`2,0,{x},0`'`` is equivalent to ``ConverterParameter='2,0,x,0'``. Both convert to a string first, then implicitly convert to Thickness at the end of the conversion.

**Comment by timothylcooke** [comment] 2023-12-12 06:08
2.2.1 is finally published.

**Closed as completed by timothylcooke** 2023-12-12 06:08 UTC
